SELECT CAR_ID, c.CAR_TYPE, FLOOR((c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100)*30) FEE
from CAR_RENTAL_COMPANY_CAR as c
join (select DISCOUNT_RATE, CAR_TYPE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN where DURATION_TYPE = '30일 이상') as p
on p.CAR_TYPE = c.CAR_TYPE 
where (c.CAR_TYPE = '세단' or c.CAR_TYPE = 'SUV') and 
FLOOR((c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100)*30) >= 500000 and 
FLOOR((c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100)*30) < 2000000 and
CAR_ID not in 
(select CAR_ID from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 where START_DATE <= '2022-11-30' and END_DATE >= '2022-11-01')
order by FEE desc, c.CAR_TYPE, c.CAR_ID desc;