SELECT HISTORY_ID,
case when END_DATE - START_DATE +1 < 7
then DAILY_FEE * (END_DATE - START_DATE+1)
when END_DATE - START_DATE +1 >= 7 and END_DATE - START_DATE +1 < 30
then DAILY_FEE * (END_DATE - START_DATE+1) * (100-(
select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN
where CAR_TYPE = '트럭' and DURATION_TYPE = '7일 이상'
)) / 100
when END_DATE - START_DATE +1 >= 30 and END_DATE - START_DATE +1 < 90
then DAILY_FEE * (END_DATE - START_DATE+1) * (100-(
select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN
where CAR_TYPE = '트럭' and DURATION_TYPE = '30일 이상'
)) / 100
when END_DATE - START_DATE +1 >= 90
then DAILY_FEE * (END_DATE - START_DATE+1) * (100-(
select DISCOUNT_RATE from CAR_RENTAL_COMPANY_DISCOUNT_PLAN
where CAR_TYPE = '트럭' and DURATION_TYPE = '90일 이상'
)) / 100
end as FEE
from CAR_RENTAL_COMPANY_CAR c,
CAR_RENTAL_COMPANY_RENTAL_HISTORY h
where c.car_id = h.car_id and 
CAR_TYPE = '트럭' 
order by FEE desc, HISTORY_ID desc;